apiVersion: v2
appVersion: "2.3.0"
name: aws-efs-csi-driver
description: A Helm chart for AWS EFS CSI Driver
icon: https://s.giantswarm.io/app-icons/aws/2/dark.svg
version: "3.2.0"
kubeVersion: ">=1.17.0-0"
home: https://github.com/giantswarm/aws-efs-csi-driver
sources:
  - https://raw.githubusercontent.com/giantswarm/aws-efs-csi-driver/v2.3.0/README.md
annotations:
  application.giantswarm.io/team: phoenix
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: phoenix
  io.giantswarm.application.upstream-chart-version: "2.3.0"
  io.giantswarm.application.upstream-chart-url: https://github.com/kubernetes-sigs/aws-efs-csi-driver
  io.giantswarm.application.restrictions.cluster-singleton: "true"
  io.giantswarm.application.restrictions.compatible-providers: "aws"
